site_name: Zircontech on AWS
site_description: 'Internal documentation - Not for public access'
site_author: 'ZirconTech'
# site_url: https://zircon-tech.github.io/cloud-ops-docs/  # Commented out to reduce discoverability

theme:
  name: material
  palette:
    # Palette toggle for light mode
  - scheme: default
    primary: blue grey
    accent: blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    # Palette toggle for dark mode
  - scheme: slate
    primary: blue grey
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.highlight
  - search.share
  - content.code.copy



markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- attr_list
- md_in_html

nav:
- Home: index.md

- Cloud Operations:
  - Methodology:
    - Multi-Account Strategy: cloud-operations/multi-account-methodology.md
    - Account Lifecycle: cloud-operations/account-lifecycle.md
    - GitOps Methodology: cloud-operations/gitops-methodology.md
    - Tagging Strategy: cloud-operations/tagging-strategy.md
    - Controls Framework: cloud-operations/preventive-detective-controls.md
    - Controls Matrix: cloud-operations/control-matrix.md
    - Third-Party Procurement: cloud-operations/third-party-procurement.md
    - Vendor Matrix: cloud-operations/vendor-matrix.md
    - Account Ownership Transfer: cloud-operations/account-ownership-transfer.md
    - Hybrid Cloud Governance: cloud-operations/hybrid-cloud-governance.md
    - Cost Allocation & Accountability: cloud-operations/cost-allocation.md
    - Planning & Forecasting: cloud-operations/planning-forecasting.md
    - Cost Reporting & Visualization: cloud-operations/cost-reporting-visualization.md
    - Resource Optimization: cloud-operations/cost-resource-optimization.md
    - Purchase-Option Optimization: cloud-operations/cost-purchase-optimization.md
    - Financial Operations: cloud-operations/financial-operations.md
    - Monitoring & Observability: cloud-operations/monitoring-observability-baseline.md
    - Hybrid Cloud Environment Observability: cloud-operations/hybrid-cloud-environment-observability.md
    - Hybrid Cloud Environment Operations: cloud-operations/hybrid-cloud-environment-operations.md
    - Dashboards & Alerts: cloud-operations/signal-analytics-visualization.md
    - Observability – Modern Apps: cloud-operations/observability-modern-apps.md
    - Security Observability & Auto-Remediation: cloud-operations/security-observability.md
    - Synthetic Monitoring: cloud-operations/synthetic-monitoring.md
    - Compliance and Auditing Overview: cloud-operations/compliance-and-auditing-overview.md
    - Define multi account strategy for the organization: cloud-operations/define-multi-account-strategy-for-the-organization.md
    - Identify, quantify, and manage risks relating to technology and business needs: cloud-operations/identify-quantify-and-manage-risks-relating-to-tec.md
    - Creating cleanroom environment for forensic analysis: cloud-operations/creating-cleanroom-environment-for-forensic-analys.md
    - Data classification and protection: cloud-operations/data-classification-and-protection.md
    - Automate controls deployment and manage them using code: cloud-operations/automate-controls-deployment-and-manage-them-using.md
    - Gather and organize the documentary evidence to support audit assessments: cloud-operations/gather-and-organize-the-documentary-evidence-to-su.md
    - Operations Management Baseline: cloud-operations/operations-management-baseline.md
    - Manage configuration items lifecycle for AWS resources: cloud-operations/manage-configuration-items-lifecycle-for-aws-resou.md
    - Automate controls deployment and manage them using code: cloud-operations/automate-controls-deployment-and-manage-them-using.md
    - Distribute and apply patch updates to infrastructure components: cloud-operations/distribute-and-apply-patch-updates-to-infrastructu.md
    - Identify, remediate and report security vulnerabilities: cloud-operations/identify-remediate-and-report-security-vulnerabili.md
    - Access compute instances in the cloud from a central location: cloud-operations/access-compute-instances-in-the-cloud-from-a-centr.md
    - ITSM Integration: cloud-operations/itsm-integration.md
    - Detect and auto-remediate incidents in real time using event triggers: cloud-operations/detect-and-auto-remediate-incidents-in-real-time-u.md
    - AIOps: cloud-operations/aiops.md
    - Centralized Change Management: cloud-operations/centralized-change-management.md
    - Customer Presentation: cloud-operations/customer-presentation.md
    - Maintaining AWS Expertise: cloud-operations/maintaining-aws-expertise.md
    - AWS Partner Solution Selling: cloud-operations/aws-partner-solution-selling.md
    - AWS Sales Engagement: cloud-operations/aws-sales-engagement.md
    - Training for Internal Personnel: cloud-operations/training-for-internal-personnel.md
    - Expected Outcomes: cloud-operations/expected-outcomes.md
    - Scope: cloud-operations/scope.md
    - Statement of Work: cloud-operations/statement-of-work.md
    - Project Manager: cloud-operations/project-manager.md
    - Change Management: cloud-operations/change-management.md
    - Customer Acceptance for Projects: cloud-operations/customer-acceptance-for-projects.md
    - Customer Satisfaction Aligned to Project Milestones: cloud-operations/customer-satisfaction-aligned-to-project-milestone.md
    - Cost Allocation Measurement and Accountability: cloud-operations/cost-allocation-measurement-and-accountability.md
    - Define Account life cycle process: cloud-operations/define-account-life-cycle-process.md
    - GitOps deployment for infrastructure: cloud-operations/gitops-deployment-for-infrastructure.md
    - Implement and enforce tagging strategy to support business needs: cloud-operations/implement-and-enforce-tagging-strategy-to-support.md
    - Effective usage of preventive and detective controls: cloud-operations/effective-usage-of-preventive-and-detective-contro.md
    - Third party products and procurement process: cloud-operations/third-party-products-and-procurement-process.md
    - AWS Account Ownership transfer: cloud-operations/aws-account-ownership-transfer.md
    - Planning and Forecasting: cloud-operations/planning-and-forecasting.md
    - Cost Reporting and Visualization: cloud-operations/cost-reporting-and-visualization.md
    - Optimize Cloud Costs Through Resource Optimization: cloud-operations/optimize-cloud-costs-through-resource-optimization.md
    - Optimize Cloud Costs Through Purchase Option Optimization: cloud-operations/optimize-cloud-costs-through-purchase-option-optim.md
    - Monitoring and Observability Baseline: cloud-operations/monitoring-and-observability-baseline.md
    - Signal Analytics and Visualization: cloud-operations/signal-analytics-and-visualization.md
    - Observability for Modern Application Architectures: cloud-operations/observability-for-modern-application-architectures.md
    - Application Performance and UX related metrics: cloud-operations/application-performance-and-ux-related-metrics.md
  - SOW Examples:
    - Multi-Account SOW: cloud-operations/sow-multi-account-strategy.md
    - GitOps SOW: cloud-operations/gitops-sow.md
  - Deliverables:
    - Forecast & TCO Workbook: cloud-operations/forecast-tco-workbook.md
    - QuickSight Dashboard Samples: cloud-operations/quicksight-dashboard-sample.md
    - RI / SP Coverage Plan: cloud-operations/ri-sp-coverage-plan.md
    - Runbook – Forecast Drivers: cloud-operations/runbook-update-forecast-drivers.md
    - Runbook – Dashboard Edit Workflow: cloud-operations/runbook-dash-edit.md

extra:
  social:
  - icon: fontawesome/brands/aws
    link: https://aws.amazon.com
    name: AWS
  # Meta tags to prevent search engine indexing
  meta:
    robots: 'noindex, nofollow, noarchive, nosnippet, noimageindex'
    googlebot: 'noindex, nofollow, noarchive, nosnippet, noimageindex'
    bingbot: 'noindex, nofollow, noarchive, nosnippet, noimageindex'

# Keep basic search functionality but discourage external indexing
plugins:
  - search

# Disable sitemap generation to prevent search engines from discovering pages
# use_directory_urls: false  # Commented out to restore normal pretty URLs
